### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by Immortalin** [haynesgt/web-circuits#1]
This is fascinating work, add a README?

**Comment by haynesgt** [comment]
There's nothing working right now.

I'm just trying to figure out how to turn an English language descriptions of a web app into a functional application.

I think context-free grammars are good enough do what I need.

**Comment by Immortalin** [comment]
Reinvent Cobol? 😂 Look into the regex generators using natural language, from a higher point to a lower point on the hierarchy. The interactive fiction stuff like Inform 7 is also pretty interesting. 

https://github.com/mbasso/natural-regex
https://en.wikipedia.org/wiki/Natural-language_programming
